version: '3.5'

services:
  redis:
    container_name: redis
    image: redis:latest 
    ports:
      - 6379:6379
    restart: unless-stopped
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - ./config/redis.conf:/usr/local/etc/redis/redis.conf